[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font Mono"
bold.style = "Bold"
italic.family = "JetBrainsMono Nerd Font Mono"
italic.style = "Italic"
bold_italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.style = "Bold Italic"
size= 15
[window]
opacity = 0.80
